### PR TITLE
Many properties now are set to required in webconsole.yaml

### PR DESCRIPTION
**Pull request by ShouheiNishi**
Many properties of objects in webconsole.yaml are defined as optional.
But go field corresponding to many of these does not has omitempty tag.
So, we add these properties are set to required.

### CODE REVIEW

**Comment by ianchen0119** [comment]
Hi @newb1er 

Please help to review PR.
Thanks.

**Comment by newb1er** [comment]
@ShouheiNish Appreciate your work!

Overall, LGTM.

But there's one more thing, I don't think we need `openapitools.json` as the generation script (`openapi-generator.sh`) overrides the configuration.

If you intended to specify the version of `openapi-generator-cli`, I suppose to bring the config into the script. I'll put another comment on that.

**Comment by newb1er** [comment]
@ShouheiNishi Here's my suggestion on the script `openapi-generator.sh`

```bash=
#/! /bin/bash

CLI_VER=${CLI_VER:-"6.6.0"}
DOCKER=${DOCKER:-0}

if [[ ${DOCKER} == "1" ]]; then
    CLI="docker run --rm -v ${PWD}:/local -w /local openapitools/openapi-generator-cli:v${CLI_VER}"
else
    CLI="openapi-generator-cli"
    ${CLI} version-manager set "${CLI_VER}"
fi

${CLI} --version
${CLI} generate \
       -i webconsole.yaml \
       -g typescript-axios \
       -o src/api

sed 's/: Time/: Date/g' src/api/api.ts >src/api/api.ts.mod
mv src/api/api.ts.mod src/api/api.ts
```

I don't have Java runtime on my machine so I turn to the Docker option.

Wait for your comments.

**Comment by ShouheiNishi** [comment]
We openapitools.json and regenerate by openapi-generator-cli 7.2.0.

**Comment by yccodr** [comment]
@ShouheiNishi Thanks for your work!

@ianchen0119 @andy89923 Please merge this PR 🙏

**Comment by andy89923** [comment]
@ShouheiNishi Please help solve the conflicts.

**Comment by ShouheiNishi** [comment]
> @ShouheiNishi Please help solve the conflicts.

Fix conflicts.

**Review by andy89923 — APPROVED** [review]
LGTM

**Pull request merged**
